apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jason.zhang@vial.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
            - name: n8n-gateway
              namespace: istio-ingress
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls-cert
  namespace: istio-ingress
spec:
  secretName: n8n-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - n8n.vial.com
